name: Bitvavo Portfolio Telegram Bot

on:
  schedule:
    - cron: '* * * * *' # Run every minute
  workflow_dispatch: # Allow manual triggering

jobs:
  send-portfolio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-bitvavo-api python-telegram-bot

    - name: Run portfolio script
      env:
        BITVAVO_API_KEY: ${{ secrets.BITVAVO_API_KEY }}
        BITVAVO_API_SECRET: ${{ secrets.BITVAVO_API_SECRET }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python bitvavo_telegram.py
